<?php
defined('C5_EXECUTE') or die(_("Access Denied."));
//
//  Note that view.php is automatically executed when the page containing your block is viewed.
//

//Prep thank-you message
//$success = (\Request::request('surveySuccess') && \Request::request('qsid') == intval($qsID));
//$thanksMsg = $survey->thankyouMsg;

//Collate all errors and put them into divs
$errorHeader = isset($formResponse) ? $formResponse : null;
$errors = isset($errors) && is_array($errors) ? $errors : array();
if (isset($invalidIP) && $invalidIP) {
	$errors[] = $invalidIP;
}
$errorDivs = '';
foreach ($errors as $error) {
	$errorDivs .= '<li class="errorsss">'.$error."</li>\n"; //It's okay for this one thing to have the html here -- it can be identified in CSS via parent wrapper div (e.g. '.formblock .error')
}

//Prep captcha
//$captcha = $surveyBlockInfo['displayCaptcha'] ? Loader::helper('validation/captcha') : false;
$captcha = Loader::helper('validation/captcha');
$formAction = $view->action('submit_form').'#formblock'.$bID;

?>
<style type="text/css">
	/*  reaches into the html generated by the captcha object to left-align the image  */
	img.ccm-captcha-image
	{
		margin-left: 0px !important;
	}
	
	#resetForm
	{
		margin-right: 20px;
		border-radius: 6px; /*Todo: hack, should be in css template for consistency */
	}
	
	.form-group.required .control-label:before 
	{ 
		color: #d00;
		content: "*";
		position: absolute;
		margin-left: -15px;	
		margin-top: 3px;	
	}
	.alert.alert-danger h5
	{
		color: inherit;
		font-weight: 700;
	}	

	.control-label
	{
		font-weight: bold;
	}
</style>

<div id="formblock<?php  echo $bID; ?>" class="ccm-block-type-form">
<form autocomplete="off" enctype="multipart/form-data" role="form" class="form" id="contact-form-<?php  echo $bID; ?>" method="post" action="<?php  echo $formAction ?>">

<?php
    if ($success)
    {
?>	
		<div class="alert alert-success">
			<?php  echo h($thankYouMessage); ?>
		</div>
<?php
    }
    elseif($errors)
    {
?>
		<div class="alert alert-danger">
			<h5><?php  echo $errorHeader; ?></h5>
			<ul>
			<?php  echo $errorDivs; /* each error wrapped in <div class="error">...</div> */ ?>
			</ul>
		</div>
<?php
    }
?>
<script type="text/javascript">
	var subjects = <?php echo $jsonData; ?>;

	$(function() {
        $('#topic').on('change', function(){
			var topicId = $(this).val();
			if (topicId > 0)
			{
            	$('#topicText').val($('#topic :selected').text());
			}
			else
			{
            	$('#topicText').val('');
			}			                
            $('#recipientEmail').val($('#topic :selected').data('email'));    
        });
        
		$('#subjectID').on('change', function(){
			var subjectId = $(this).val();
			if (subjectId > 0)
			{
            	$('#subjectText').val($('#subjectID :selected').text());
			}
			else
			{
            	$('#subjectText').val('');
			}
			var topics = [];
			for (index = 0; index < subjects.length; index++) 
			{
				if (subjects[index].id == subjectId)
				{
					if (subjects[index].topics.length > 1)
					{
						subjects[index].topics.sort(function(a, b) {
							var string1 = '' + a.sortOrder + a.description;
							var string2 = '' + b.sortOrder + b.description;
							return string1.localeCompare(string2);
						});
						$('#topic').find('option:not(:first)').remove();
						for (i = 0; i < subjects[index].topics.length; i++)
						{
							var topic = subjects[index].topics[i];
							$('#topic').append($("<option></option>").attr("value", topic.id).attr("data-email", topic.recipientEmail).text(topic.description));
						}
						//$('#topic').find('option:first').attr("selected","selected");
						$('#div-topics').show();
                        $("#topic").prop("disabled", false);
                        $('#div-topics select option[value="' + <?php echo $topicID; ?> + '"]').prop('selected', true);
                        $('#topic').trigger('change');
						return;
					}
					else
					{
                        $('#div-topics').hide();
                        $("#topic").prop("disabled", true);                        
                        $('#topic').val(0);
                        $('#recipientEmail').val($('#subjectID :selected').data('email'));    
						return;
					}
				}
			}
			//alert('not found');
		});
		
		//$('#subjectID').find('option:first').attr("selected", "selected");
        $('#subjectID').trigger('change');
	});
</script>

	<div class="fields">
        <input type="hidden" id="recipientEmail" name="recipientEmail" class="form-control" value="<?php echo $this->recipientEmail; ?>" />
        <input type="hidden" id="subjectText" name="subjectText" class="form-control" value="<?php echo $this->subjectText; ?>" />
        <input type="hidden" id="topicText" name="topicText" class="form-control" value="<?php echo $this->topicText; ?>" />
		<div class="form-group required <?php echo $errorDetails['subjectID'] ? 'has-error' : ''?>">
			<label class="control-label" for="subjectID">Category:</label>
			<select id="subjectID" name="subjectID" class="form-control">
				<option data-email="" value="0">--- Please select a Category ---</option>
	<?php  
	foreach ($subjectEmails as $subjectEmail)
	{
        $selected = $subjectID == $subjectEmail["seID"] ? "selected=\"selected\"" : "";
		if (intval($subjectEmail["parentSeID"]) == 0)
		{
?>
				<option data-email="<?php echo $subjectEmail["recipientEmail"]?>" value="<?php echo $subjectEmail["seID"]?>" <?php echo $selected; ?> ><?php echo $subjectEmail["description"]?></option>
<?php
		}
	}
?>
			</select>
		</div>	
		<div id="div-topics" style="display: none;" class="form-group required <?php echo $errorDetails['topic'] ? 'has-error' : ''?> required">
			<label class="control-label" for="topic">Topic:</label>
			<select id="topic" name="topic" class="form-control" autocomplete="off" >
				<option data-email="" value="0">--- Please also select a Topic ---</option>
			</select>
		</div>	
		<div class="form-group required <?php echo $errorDetails['name'] ? 'has-error' : ''?>">
			<label class="control-label" for="name">Name:</label>
			<input type="text" id="name" name="name" class="form-control" value="<?php echo h($name); ?>" autocomplete="off" />
		</div>	
		<div class="form-group required <?php echo $errorDetails['email'] ? 'has-error' : ''?>">
			<label class="control-label" for="email">Email:</label>
			<input type="text" id="email" name="email" class="form-control" value="<?php echo h($email); ?>" autocomplete="off" />
		</div>	
		
		<div class="row">
			<div class="col-xs-6">
				<div class="form-group <?php echo $errorDetails['preferredMethod'] ? 'has-error' : ''?>">
					<label class="control-label" for="preferredMethod">Preferred Contact Method:</label>
					<select id="preferredMethod" name="preferredMethod" class="form-control" autocomplete="off" >
						<option value="Phone" <?php echo $preferredMethod == 'Phone' ? "selected=\"selected\"" : "";?>>Telephone</option>
						<option value="Email" <?php echo $preferredMethod == 'Email' ? "selected=\"selected\"" : "";?>>Email</option>
						<option value="Mail"> <?php echo $preferredMethod == 'Mail'  ? "selected=\"selected\"" : "";?>Mail</option>
					</select>
				</div>	
			</div>	
			<div class="col-xs-6">
				<div class="form-group <?php echo $errorDetails['preferredTime'] ? 'has-error' : ''?>">
					<label class="control-label" for="preferredTime">Preferred Contact Time:</label>
					<select id="preferredTime" name="preferredTime" class="form-control" autocomplete="off" >
						<option value="Morning"   <?php echo $preferredTime == 'Morning'   ? "selected=\"selected\"" : "";?>>Morning</option>
						<option value="Afternoon" <?php echo $preferredTime == 'Afternoon' ? "selected=\"selected\"" : "";?>>Afternoon</option>
						<option value="Evening"   <?php echo $preferredTime == 'Evening'   ? "selected=\"selected\"" : "";?>>Evening</option>
					</select>
				</div>	
			</div>	
		</div>	
		
		<div class="row">
			<div class="col-xs-6">
				<div class="form-group required <?php echo $errorDetails['dayPhone'] ? 'has-error' : ''?>">
					<label  class="control-label" for="dayPhone">Day Phone:</label>
					<input type="text" id="dayPhone" name="dayPhone" class="form-control" value="<?php echo h($dayPhone); ?>" autocomplete="off" />
				</div>	
			</div>	
			<div class="col-xs-6">
				<div class="form-group <?php echo $errorDetails['eveningPhone'] ? 'has-error' : ''?>">
					<label class="control-label" for="eveningPhone">Evening Phone:</label>
					<input type="text" id="eveningPhone" name="eveningPhone" class="form-control" value="<?php echo h($eveningPhone); ?>" autocomplete="off" />
				</div>	
			</div>	
		</div>	
		
		<div class="form-group required <?php echo $errorDetails['message'] ? 'has-error' : ''?>">
			<label class="control-label" for="message">Message:</label>
			<textarea id="message" rows="5" cols="40" name="message" class="form-control" /><?php echo h($message); ?></textarea>
		</div>	
		
<?php  
	if ($captcha)
	{
?>
		<div class="form-group captcha <?php echo $errorDetails['captcha'] ? 'has-error' : ''?>">
			<div><?php  $captcha->display(); ?></div>
			<div><?php  $captcha->showInput(array('autocomplete' => 'off')); ?></div>
		</div>
<?php
	}
?>
	</div><!-- .fields -->
	
	<div class="form-group">
		<a id="resetForm" href="<?php echo $currentUrl; ?>" class="btn btn-danger" role="button"><?php  echo h(t("Reset Form")); ?></a>		
		<input type="submit" name="Submit" class="btn btn-primary" value="<?php  echo h(t("Send Message")); ?>" />
	</div>
	
</form>
</div><!-- .formblock -->
